[package]
name = "r_bilio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.0", features = ["postgres"] }
dotenvy = "0.15"
chrono = "0.4.24"
console = "0.15"
crypto-hash = "0.3.4"
regex = "1.5.4"